#!/bin/sh

set -e

self_dir=$(dirname $(readlink -f "$0"))
MINIPRO="$self_dir/minipro"
MINIPRO_QUERY_DB="$self_dir/minipro-query-db"

"$MINIPRO" -l | (
	sep=""
	echo "["
	while read pn; do
	      echo -n "$sep"
	      "$MINIPRO_QUERY_DB" -j "$pn"
	      sep=",\n"
	done
	echo "]"
)
